[workspace]
version = 1
root = "." # default, current working directory
config-dir = "config" # default
generated-dir = ".gears" # default

[apps.app1.dev]
config = "app1-dev.yml" # relative from config_dir
modules = [
    {
        name = "module1",
        source = "local", # local | remote
        version = "1.2.0", # required for remote
        package = "crate1",
    },
    {
        name = "module2",
        source = "remote",
        version = "0.1.0",
        package = "crate2",
        registry = "https://crates.io" # optional, by default is crates.io
    }
]
run = {
    watch = { enabled = true }, # this is the default
    fips = false,
    otel = true
}
build = {
    name = "app1", # override env name
    profile = "debug"
}

[apps.app1.dev.lint]
dylint = {
    enabled = true,
    skip = [
        "de0101_no_serde_in_contract",
        "de0110_no_schema_for_on_gts_structs",
    ],
}
clippy = true # by default
fmt = true # by default
feature-set-test = true # inherits the feature set to test


[apps.app1.dev.test]
runner = "nextest"
feature-set = {
    "module1" = [
        ["unit", "integration"],
        ["sqlite"],
        ["postgres"],
        ["fips"],
        false # disable all features
    ],
    "module2" = true, # enable all features
}

[apps.app1.prod]
config = "app1-prod.yml"
modules = [
    {
        name = "module1",
        source = "local", # local | remote | registry
        version = "1.2.0", # required for remote and registry
        package = "crate1",
    },
    {
        name = "module2",
        source = "remote",
        version = "0.1.0",
        package = "crate2",
    }
]
run = {
    watch = { enabled = false },
    fips = true,
    otel = true
}
build = {
    name = "app1", # override env name
    profile = "release"
}
# inherit lint and test from dev
lint = { ref = "dev", }
test = { ref = "dev", }

[templates.module.background-worker]
source = "git"
url = "ssh://github.com/username/repository.git"
revision = "eb5a0f5d"

[templates.config.grpc-service]
source = "local"
path = "templates/grpc-service"

[templates.agents.custom-agent]
source = "git"
url = "ssh://github.com/constructorfabric/cf-template-rust.git"
tag = "0.2"
subfolder = "Agents/custom-agent"
