name: CI

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'crates/cargo-gears/**/*.rs'
      - 'crates/cargo-gears/**/*.toml'
      - 'crates/cargo-gears-core/**/*.rs'
      - 'crates/cargo-gears-core/**/*.toml'
      - 'crates/cargo-gears-macros/**/*.rs'
      - 'crates/cargo-gears-macros/**/*.toml'
      - 'Cargo.lock'
      - '.clippy.toml'
      - 'rust-toolchain.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Format, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2

      - run: cargo fmt --check
      - run: cargo clippy --workspace -- -D warnings
      - run: cargo test --workspace
